on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing Job
    steps:
      - name: List of the GitHub Actions environment variables on Ubuntu
        run: echo "Test"
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/action-test@v14
        with:
          slack_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: "Github Action Completed for ${{ github.repository	 }} with Build Number ${{ github.run_number }} and the outcome is  ${{ needs.build.result }}."
