on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Message
    steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/action-test@v13
        with:
          slack_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: format('Hello {0} {1} {2}', 'Mona', 'the', $GITHUB_RUN_NUMBER)


