on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Message
    steps:
      - name: List of the GitHub Actions environment variables on Ubuntu
        run: env
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/action-test@v14
        with:
          slack_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: "Github Action Completed with Build Number ${{ github.run_number }}"


