on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Message
    steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/action-test@v13
        with:
          slack_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: $GITHUB_RUN_NUMBER
