on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing Message
    steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/action-test@v8
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          message: "Github Action Got Completed"
